import json
import os

REPO_ROOT = "/Users/mahamudc/Documents/NetSpout"
EV_DIR = os.path.join(REPO_ROOT, "docs", "acceptance", "evidence", "gate11e")
IMG_DIR = os.path.join(REPO_ROOT, "docs", "acceptance", "images", "gate11e")
os.makedirs(EV_DIR, exist_ok=True)
os.makedirs(IMG_DIR, exist_ok=True)

scorecard_file = os.path.join(REPO_ROOT, "docs", "acceptance", "gate11e_native_flow_scorecard.json")
with open(scorecard_file, "r") as f:
    scorecard = json.load(f)

# 1. Native flow discovery
with open(os.path.join(EV_DIR, "01_native_flow_discovery.txt"), "w") as f:
    f.write(
        "Discovery Source: README.md Section ⚡ Native Flow Telemetry (NetFlow v9 & IPFIX)\n"
        "Guide: docs/guides/NATIVE_FLOW_QUICKSTART.md\n"
        "CLI: deploy/collector/manage_collector.py\n"
        "UI: Telemetry Pipelines Modal -> Card 5 (Native Flow Telemetry Pipeline)\n"
    )

# 2. Fidelity explanation
with open(os.path.join(EV_DIR, "02_fidelity_explanation.txt"), "w") as f:
    f.write(
        "Fidelity Badge: NATIVE TRANSPORT\n"
        "Transport: Wire-compliant RFC 3954 (NetFlow v9) & RFC 7011 (IPFIX) binary UDP datagrams\n"
        "Payload Semantics: Simulated network flows generated by NetSpout engine\n"
        "Hardware Implication: None. NetSpout explicitly disclaims physical router/switch hardware export.\n"
    )

# 3. Collector preflight
with open(os.path.join(EV_DIR, "03_collector_preflight.json"), "w") as f:
    json.dump(scorecard["preflight"], f, indent=2)

# 4. Healthy pipeline
with open(os.path.join(EV_DIR, "04_healthy_pipeline.json"), "w") as f:
    json.dump(scorecard["baseline"], f, indent=2)

# 5. NetFlow v9 execution
with open(os.path.join(EV_DIR, "05_netflow_v9_execution.json"), "w") as f:
    json.dump(scorecard["netflow_v9"], f, indent=2)

# 6. NetFlow collector evidence
with open(os.path.join(EV_DIR, "06_netflow_collector_evidence.json"), "w") as f:
    json.dump({
        "collector_observed": scorecard["netflow_v9"]["collector_observed"],
        "records_decoded": scorecard["netflow_v9"]["collector_records_decoded"]
    }, f, indent=2)

# 7. NetFlow Splunk evidence
with open(os.path.join(EV_DIR, "07_netflow_splunk_evidence.json"), "w") as f:
    json.dump({
        "splunk_records_observed": scorecard["netflow_v9"]["splunk_records_observed"],
        "run_id": scorecard["netflow_v9"]["run_id"]
    }, f, indent=2)

# 8. IPFIX execution
with open(os.path.join(EV_DIR, "08_ipfix_execution.json"), "w") as f:
    json.dump(scorecard["ipfix"], f, indent=2)

# 9. IPFIX collector evidence
with open(os.path.join(EV_DIR, "09_ipfix_collector_evidence.json"), "w") as f:
    json.dump({
        "collector_observed": scorecard["ipfix"]["collector_observed"],
        "records_decoded": scorecard["ipfix"]["collector_records_decoded"]
    }, f, indent=2)

# 10. IPFIX Splunk evidence
with open(os.path.join(EV_DIR, "10_ipfix_splunk_evidence.json"), "w") as f:
    json.dump({
        "splunk_records_observed": scorecard["ipfix"]["splunk_records_observed"],
        "run_id": scorecard["ipfix"]["run_id"]
    }, f, indent=2)

# 11. Copyable SPL
raw_spl = scorecard["splunk_investigation"]["raw_events_spl"]
stats_spl = scorecard["splunk_investigation"]["stats_spl"]
with open(os.path.join(EV_DIR, "11_copyable_spl.txt"), "w") as f:
    f.write(f"Raw Events SPL:\n{raw_spl}\n\nAggregated Stats SPL:\n{stats_spl}\n")

# 12. Collector offline failure
with open(os.path.join(EV_DIR, "12_collector_offline_failure.json"), "w") as f:
    json.dump(scorecard["failures"]["collector_offline"], f, indent=2)

# 13. Forwarder offline failure
with open(os.path.join(EV_DIR, "13_forwarder_offline_failure.json"), "w") as f:
    json.dump(scorecard["failures"]["forwarder_offline"], f, indent=2)

# 14. Splunk offline failure
with open(os.path.join(EV_DIR, "14_splunk_offline_failure.json"), "w") as f:
    json.dump(scorecard["failures"]["splunk_offline_simulation"], f, indent=2)

# 15. Recovery
with open(os.path.join(EV_DIR, "15_recovery.json"), "w") as f:
    json.dump(scorecard["template_lifecycle"], f, indent=2)

# 16. Final validation
with open(os.path.join(EV_DIR, "16_final_validation.json"), "w") as f:
    json.dump({
        "determination": scorecard["determination"],
        "concurrency": scorecard["concurrency"],
        "security": scorecard["security"],
        "performance": scorecard["performance"]
    }, f, indent=2)

print("Successfully written 16 evidence artifacts to:", EV_DIR)
