receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 100

exporters:
  splunk_hec:
    token: "00000000-0000-0000-0000-000000000000"
    endpoint: "https://splunk-netspout:8088/services/collector"
    insecure_skip_verify: true
    source: "otel:collector"
    sourcetype: "otel:telemetry"
    index: "cisco_mdt_metrics"
    splunk_app_name: "NetSpout"
    splunk_app_version: "2.0.0"
  
  debug:
    verbosity: basic

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [splunk_hec, debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [splunk_hec, debug]
