FROM python:3.12-alpine

# Hardened non-root user
RUN addgroup -g 10001 netspout && \
    adduser -u 10001 -G netspout -s /bin/sh -D netspout

WORKDIR /app

COPY forwarder.py /app/forwarder.py
RUN chmod 755 /app/forwarder.py && chown -R netspout:netspout /app

USER 10001:10001

EXPOSE 8082

ENTRYPOINT ["python3", "-u", "/app/forwarder.py"]
