FROM python:3.12-alpine@sha256:4c47124a8391cb7a9f571164147d154777cf012a4ece5f86097130d7a4478111

# Hardened non-root user
RUN addgroup -g 10001 netspout && \
    adduser -u 10001 -G netspout -s /bin/sh -D netspout

WORKDIR /app

COPY forwarder.py /app/forwarder.py
RUN chmod 755 /app/forwarder.py && chown -R netspout:netspout /app

USER 10001:10001

EXPOSE 8082

ENTRYPOINT ["python3", "-u", "/app/forwarder.py"]
