[launcher]
author = Mahamudul Chowdhury (mchowdhury@splunk.com)
description = NetSpout: Splunk-Native Network Telemetry Simulation, Interactive SPL Playground, OpenConfig MDT Engine, 30-Vendor TA Ecosystem, and NOC/SOC Metric Matrix
version = 2.0.0

[package]
id = netspout
check_for_updates = 0

[ui]
is_visible = 1
label = NetSpout
show_in_nav = 1

[install]
is_configured = 1
state = enabled
build = 20260919
