[netspout_streamer://default]
disabled = 1
interval = 5
ecosystem_mode = mixed_vendor
scenario = mixed_edge_breach
target_hec_url = http://127.0.0.1:8888/services/collector
metric_index = cisco_mdt_metrics
event_index = idx_network_ops
