[netspout_streamer://default]
disabled = 1
interval = 5
ecosystem_mode = mixed_vendor
scenario = mixed_edge_breach
target_hec_url = https://127.0.0.1:8088/services/collector
metric_index = cisco_mdt_metrics
event_index = idx_network_ops

[http]
disabled = 0
port = 8088
enableSSL = 1
dedicatedIoThreads = 2
maxSockets = 10000
maxThreads = 0

[http://netspout_hec_token]
disabled = 0
token = 00000000-0000-0000-0000-000000000000
index = idx_network_ops
indexes = idx_network_ops,idx_security_fw,idx_wireless_ops,idx_performance_metrics,cisco_mdt_metrics,cisco_duo,netops_logs,main

[http://netspout_metric_token]
disabled = 0
token = 00000000-0000-0000-0000-000000000000
index = cisco_mdt_metrics
indexes = cisco_mdt_metrics,idx_performance_metrics

[udp://514]
connection_host = dns
index = idx_network_ops
sourcetype = syslog
no_priority_stripping = true

[tcp://514]
connection_host = dns
index = idx_network_ops
sourcetype = syslog


