[cisco_secure_firewall]
definition = sourcetype="cisco:sfw:estreamer"
iseval = 0

[security_content_ctime(1)]
args = field
definition = convert timeformat="%Y-%m-%dT%H:%M:%S" ctime($field$)
iseval = 0

[cisco_secure_firewall___react_server_components_rce_attempt_filter]
definition = search *
iseval = 0
