[cisco:sfw:estreamer]
KV_MODE = json
EVAL-signature_id = coalesce(signature_id, SignatureID)
EVAL-signature = coalesce(signature, IntrusionRuleMessage)
EVAL-src = coalesce(src, InitiatorIP)
EVAL-dest = coalesce(dest, ResponderIP)
EVAL-dest_port = coalesce(dest_port, ResponderPort)
EVAL-rule = coalesce(rule, FirewallRule)
EVAL-transport = coalesce(transport, Protocol)
EVAL-app = coalesce(app, Application)
