[script:netspout_api]
match = /netspout
script = netspout_rest_handler.py
scripttype = persist
handler = netspout_rest_handler.NetSpoutRestHandler
requireAuthentication = true
output_modes = json
passHttpHeaders = true
passPayload = true

[script:datablaster_execution]
match = /datablaster/execute
script = datablaster_rest.py
scripttype = persist
handler = datablaster_rest.DataBlasterRestHandler
requireAuthentication = true
output_modes = json
passPayload = true
passHttpHeaders = true
python.version = python3
