[script:netspout_api]
match = /netspout
script = netspout_rest_handler.py
scripttype = persist
handler = netspout_rest_handler.NetSpoutRestHandler
requireAuthentication = true
output_modes = json
passHttpHeaders = true
passPayload = true
